module.exports.REPLACEMENT = {
  0: { set: 'base', sticker: 'men' },
  1: { set: 'base', sticker: 'square' },
  2: { set: 'base', sticker: 'bridge' },
  3: { set: 'base', sticker: 'ikea' },
  4: { set: 'base', sticker: 'bugr' },
  5: { set: 'base', sticker: 'monum' },
  6: { set: 'base', sticker: 'opera' },
  7: { set: 'base', sticker: 'forest' },
  8: { set: 'base', sticker: 'empty' },
  9: { set: 'base', sticker: 'empty' },
  10: { set: 'base', sticker: 'road' },
  11: { set: 'base', sticker: 'chicken' },
  12: { set: 'base', sticker: 'camp' },
  13: { set: 'base', sticker: 'fastfood' },
  14: { set: 'base', sticker: 'beer' },
  15: { set: 'base', sticker: 'pancake' },
  16: { set: 'base', sticker: 'rocks' },
  17: { set: 'real', sticker: 'swamp' },
  18: { set: 'real', sticker: 'skull' },
  19: { set: 'base', sticker: 'crap' },
  20: { set: 'pin', sticker: 'start' },
  21: { set: 'pin', sticker: 'p1' },
  22: { set: 'pin', sticker: 'p2' },
  23: { set: 'pin', sticker: 'p3' },
  24: { set: 'pin', sticker: 'p4' },
  25: { set: 'pin', sticker: 'p5' },
  26: { set: 'pin', sticker: 'p6' },
  27: { set: 'pin', sticker: 'finish' },
  29: { set: 'pin', sticker: 'danger' },
  30: { set: 'pin', sticker: 'question' },
};

module.exports.MAPS = {
  'watercolor': 'BLANK',
  'darq': 'BLANK',
  'default': 'DGIS',
  'osm': 'DEFAULT',
  'hot': 'HOT',
  'blank': 'BLANK',
  'sat': 'DEFAULT',
  'ymap': 'DEFAULT',
  'ysat': 'DEFAULT',
};
