export const MODES = {
  POLY: 'POLY',
  STICKERS: 'STICKERS',
  ROUTER: 'ROUTER',
  SHOTTER: 'SHOTTER',
  TRASH: 'TRASH',
  NONE: 'NONE',
  LOGO: 'LOGO',
  SAVE: 'SAVE',
  CONFIRM_CANCEL: 'CONFIRM_CANCEL',
  PROVIDER: 'PROVIDER',
};
