const P = 'MAP'

export const MAP_ACTIONS = {
  SET_MAP: `${P}-SET_MAP`,
  SET_PROVIDER: `${P}-SET_PROVIDER`,
  SET_ROUTE: `${P}-SET_ROUTE`,

  SET_STICKER: `${P}-SET_STICKER`,
  DROP_STICKER: `${P}-DROP_STICKER`,

  MAP_CLICKED: `${P}-MAP_CLICKED`
}