export const ACTIONS = {
  SET_USER: 'SET_USER',
  USER_LOGOUT: 'USER_LOGOUT',

  SET_EDITING: 'SET_EDITING',
  SET_MODE: 'SET_MODE',
  SET_DISTANCE: 'SET_DISTANCE',
  SET_CHANGED: 'SET_CHANGED',
  SET_ROUTER_POINTS: 'SET_ROUTER_POINTS',
  SET_ACTIVE_STICKER: 'SET_ACTIVE_STICKER',
  SET_LOGO: 'SET_LOGO',
  SET_TITLE: 'SET_TITLE',
  SET_ADDRESS: 'SET_ADDRESS',

  START_EDITING: 'START_EDITING',
  STOP_EDITING: 'STOP_EDITING',
};
